# Form implementation generated from reading ui file 'D:\TranThanhThinh_K234111418_K234111E\chartplot\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 468)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 160, 101, 16))
        self.label.setObjectName("label")
        self.lineEditDataset = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDataset.setGeometry(QtCore.QRect(250, 150, 301, 31))
        self.lineEditDataset.setObjectName("lineEditDataset")
        self.pushButtonBrowser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBrowser.setGeometry(QtCore.QRect(560, 150, 93, 28))
        self.pushButtonBrowser.setObjectName("pushButtonBrowser")
        self.pushButtonOpen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOpen.setGeometry(QtCore.QRect(180, 230, 191, 41))
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.pushButtonSaveToHTML = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSaveToHTML.setGeometry(QtCore.QRect(410, 230, 191, 41))
        self.pushButtonSaveToHTML.setObjectName("pushButtonSaveToHTML")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trần Thanh Thinh - K234111418"))
        self.label.setText(_translate("MainWindow", "Choose Dataset:"))
        self.pushButtonBrowser.setText(_translate("MainWindow", "..."))
        self.pushButtonOpen.setText(_translate("MainWindow", "Open Chart in Browser"))
        self.pushButtonSaveToHTML.setText(_translate("MainWindow", "Save Chart to HTML file"))
